### ISSUE TITLE
Superposición de precio y descuento en los articulos 

### ISSUE THREAD

**Issue by DesireeHolowiniec** [PabloKr/mercado-liebre#2]
![image](https://github.com/PabloKr/mercado-liebre/assets/136195327/347e51bf-82f6-4117-a3bd-82075bc191ed)

Poner justify-content: space between para que no se superpongan

![image](https://github.com/PabloKr/mercado-liebre/assets/136195327/7b538d5c-458a-4059-9c77-0249b6cc5435)

**Comment by PabloKr** [comment]
Problema solucionado.
