### ISSUE TITLE
Errores de Register

### ISSUE THREAD

**Issue by Selik98** [PabloKr/mercado-liebre#3]
Etiqueta span aparece al lado de los radio buttons alterando su posicion.

Al ser una opcion de radio deberia llevar otro mensaje distinto en 1 solo lado

![image](https://github.com/PabloKr/mercado-liebre/assets/117553550/72fac075-15cc-4868-a4ba-c183c89ab07a)

**Comment by PabloKr** [comment]
Corregido.
